### ISSUE TITLE
Failed with Technical Error

### ISSUE THREAD

**Issue by daham123** [cTrader-Guru/Bifrost#1]
Hi Leonardo, first of all thx a lot for the cool bifrost tool --> perfect for running two ctrader instances on one PC.

Its executing the copied trades open/close just fine, but then sometimes I get:
"Executing Market Order to Buy 20 GER40.cash (MR: 3) FAILED with error "TechnicalError"

**Comment by LeonardoCiaccio** [comment]
Did you translate the pair correctly? if yes, you need to ask your broker
